services:
  mongodb:
    container_name: mongodb-servidor
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_APP_USER=${MONGO_APP_USER}
      - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    external: true